version: "3.8"

services:
  postgres-service:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=warehouse_control
    ports:
      - "5433:5432"
    volumes:
      - ./migration/001_create_database_up.sql:/docker-entrypoint-initdb.d/001_create_database_up.sql


  app:
    build: ./
    ports:
      - "8081:8080"
    depends_on:
      - postgres-service
    restart: on-failure