server:
  address: ":8080"
  timeout: 4s
  idle_timeout: 60s
  shutdown_timeout: 10s

db:
  host: "postgres-service" # "localhost"  
  port: 5432               
  username: "postgres"
  name: "sales_tracker"
  password: "postgres"